### ISSUE TITLE
Import Models at runtime

### ISSUE THREAD

**Issue by HeadClot** [ryanjon2040/UE4-Map-Editor#1]
Hey,
Would it be possible to import models at runtime?

I am currently planning on modifying the UE4 Map Editor for my own game and forking the changes back over to here.

Thank you for your time,

HeadClot

**Comment by ryanjon2040** [comment]
You mean import FBX models?

**Comment by HeadClot** [comment]
Yep, Import .FBX models at run time.

**Comment by ryanjon2040** [comment]
It should be possible but then you have to write your own FBX importer.
