### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by MichaelJBrune** [ryanjon2040/UE4-Map-Editor#2]
Hello,

Would love to use this but there is no license for this work meaning you own all the copyrights for it and I can't use it legally.

Thanks,
Michael Brune

**Comment by ryanjon2040** [comment]
Hi @MJBrune There is no license for this. Feel free to use it in your projects.

**Comment by MichaelJBrune** [comment]
Hey Ryan,

Would feel a lot better if you had a license on this in clear terms, Even if its just http://www.wtfpl.net its better than no license as no license assumes you retain all rights in the USA so I couldn't legally use your code. There is a bit of a wiki page on some of the US law https://en.wikipedia.org/wiki/Software_copyright#United_States_practice if interested.

Thanks again,
Michael Brune

**Comment by ryanjon2040** [comment]
Hi @MJBrune ,

As per your request, I've added a License to this project. You can see it here: https://github.com/ryanjon2040/UE4-Map-Editor/blob/master/LICENSE

**Comment by MichaelJBrune** [comment]
Hey @ryanjon2040 Thank you a ton! Not only have you made your code mode usable to me you have turned me to a new license I've not heard before. Thanks again! :D
